volumes:
  todos-vol:

services:
  
  python:
    
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pgsql
    
    ports:
      - 5000:5000

    volumes:
      - . :/usr/src/app

  pgsql:
    image: postgres:12.11
    environment:
      POSTGRES_PASSWORD: password #not recommanded to keep password like this, test purpose only
      POSTGRES_USER: postgres # test purpose only
      POSTGRES_DB: tododb
      POSTGRES_HOST: localhost
      DATABASE_PORT: 5432
    #volumes:
      #- test-vol:/var/lib/postgresql/data
    #ports:
      #- 5432:5432
